apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-operator
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: sandboxes
